/// Month dimension for the Canadian acute-activity layer, 2024-07 to 2026-06.
///
/// This is deliberately a second date table rather than a reuse of dim_month,
/// and the reason is a data range mismatch that would otherwise fail silently.
/// dim_month is generated for the revenue-cycle claims period (2025-07 onward,
/// 13 months). The inpatient abstracts span 24 months from 2024-07, so twelve of
/// them fall outside dim_month entirely — relating discharge_month to it would
/// push half the authority's activity into a blank row and every month-sliced
/// visual would quietly under-report, with nothing on the canvas to say so.
///
/// The alternative, widening dim_month backwards, would hang twelve empty months
/// off the left of every revenue-cycle chart that already works. The two subject
/// areas genuinely cover different periods and are never cross-filtered, so they
/// get their own conformed calendars.
table dim_activity_month
	lineageTag: c8a10001-0000-4000-8000-000000000001

	column month
		dataType: string
		sortByColumn: month_start
		lineageTag: c8a10001-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: month

	column month_start
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c8a10001-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: month_start

		annotation UnderlyingDateTimeDataType = Date

	column fiscal_year
		dataType: string
		lineageTag: c8a10001-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: fiscal_year

	partition dim_activity_month = m
		mode: import
		source =
				let
				    Months = List.Transform({0..23}, each Date.AddMonths(#date(2024, 7, 1), _)),
				    ToTable = Table.FromList(Months, Splitter.SplitByNothing(), {"month_start"}),
				    Typed = Table.TransformColumnTypes(ToTable, {{"month_start", type date}}),
				    AddedLabel = Table.AddColumn(Typed, "month", each Date.ToText([month_start], "yyyy-MM"), type text),
				    AddedFiscal = Table.AddColumn(AddedLabel, "fiscal_year", each
				        let y = Date.Year([month_start]), m = Date.Month([month_start])
				        in if m >= 4 then Text.From(y) & "/" & Text.End(Text.From(y + 1), 2)
				           else Text.From(y - 1) & "/" & Text.End(Text.From(y), 2), type text),
				    Reordered = Table.ReorderColumns(AddedFiscal, {"month", "month_start", "fiscal_year"})
				in
				    Reordered
