table dim_month
	lineageTag: b2337673-31eb-403b-bb4c-6d01dc1f0f99

	column month
		dataType: string
		lineageTag: 5ddc83a6-fefc-4988-92a8-a419c1a89048
		summarizeBy: none
		sourceColumn: month
		sortByColumn: month_start

	column month_start
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 18a71f0b-02c2-4be0-b3f1-d50da842dd2a
		summarizeBy: none
		sourceColumn: month_start

		annotation UnderlyingDateTimeDataType = Date

	partition dim_month = m
		mode: import
		source =
				let
				    // The calendar is derived from the claims, never typed in. This table was pinned to
				    // thirteen months from 2025-07 while the rebuilt seed submits claims across two
				    // years from 2024-07, so a full year of cash collected landed in a (Blank) month
				    // that still totalled correctly - a chart wrong in the one way a total cannot show.
				    Source = Csv.Document(File.Contents(DataPath & "\data\fact_claims.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Submitted = List.RemoveNulls(List.Transform(Table.Column(Promoted, "submitted_date"), each try Date.From(_) otherwise null)),
				    First = Date.StartOfMonth(List.Min(Submitted)),
				    Last = Date.StartOfMonth(List.Max(Submitted)),
				    Span = (Date.Year(Last) - Date.Year(First)) * 12 + Date.Month(Last) - Date.Month(First),
				    Months = List.Transform({0..Span}, each Date.AddMonths(First, _)),
				    ToTable = Table.FromList(Months, Splitter.SplitByNothing(), {"month_start"}),
				    Typed = Table.TransformColumnTypes(ToTable, {{"month_start", type date}}),
				    AddedLabel = Table.AddColumn(Typed, "month", each Date.ToText([month_start], "yyyy-MM"), type text),
				    Reordered = Table.ReorderColumns(AddedLabel, {"month", "month_start"})
				in
				    Reordered
